/**
 * One-time generator for src/layout/geometry/preset-shape-data.ts.
 *
 * Source: ECMA-376 5th edition Part 1 distribution (December 2016),
 * inside OfficeOpenXML-DrawingMLGeometries.zip → presetShapeDefinitions.xml.
 * The zip is embedded in https://ecma-international.org/wp-content/uploads/ECMA-376-1_5th_edition_december_2016.zip
 * and is mirrored by Apache POI (Apache-2.0). Download it once and pass the
 * XML path:
 *
 *   pnpm tsx scripts/generate-preset-shapes.ts <path-to-presetShapeDefinitions.xml>
 *
 * The output is static spec data — regenerate only when the ECMA source
 * updates. ahLst (adjust handles) and cxnLst (connection sites) are dropped:
 * nothing consumes them yet; textRect values that equal the trivial
 * "l t r b" are skipped as well.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

type PathFill = "norm" | "none" | "darken" | "darkenLess" | "lighten" | "lightenLess";

interface PathDef {
  w: number;
  h: number;
  fill: PathFill;
  stroke: boolean;
  d: string;
}

interface ShapeDef {
  av: string[];
  gd: string[];
  rect?: string;
  paths: PathDef[];
}

const xmlPath = process.argv[2];
if (!xmlPath) {
  console.error("usage: tsx scripts/generate-preset-shapes.ts <presetShapeDefinitions.xml>");
  process.exit(1);
}

const xml = readFileSync(resolve(xmlPath), "utf8").replace(/^﻿/, "");

const attr = (tag: string, name: string): string | undefined =>
  tag.match(new RegExp(`${name}="([^"]*)"`))?.[1];

const guides = (block: string, tag: "avLst" | "gdLst"): string[] => {
  const list = block.match(new RegExp(`<${tag}[^>]*>([\\s\\S]*?)</${tag}>`));
  if (!list) return [];
  return [...list[1].matchAll(/<gd name="([^"]*)" fmla="([^"]*)"/g)].map(
    ([, name, fmla]) => `${name} ${fmla}`,
  );
};

// Structured path encoding, resolved by the runtime evaluator one token at a
// time: m(2) l(2) c(6) q(4) a(4: wR hR stAng swAng) x(close) — operands are
// guide names or numeric literals in the path's coordinate space.
const pt = (s: string): string => ` ${attr(s, "x") ?? "0"} ${attr(s, "y") ?? "0"}`;

const encodePath = (tag: string, body: string): PathDef => {
  let d = "";
  const ops = body.match(
    /<moveTo>[\s\S]*?<\/moveTo>|<lnTo>[\s\S]*?<\/lnTo>|<cubicBezTo>[\s\S]*?<\/cubicBezTo>|<quadBezTo>[\s\S]*?<\/quadBezTo>|<arcTo[^>]*\/>|<close\s*\/>/g,
  );
  for (const op of ops ?? []) {
    if (op.startsWith("<moveTo>")) d += ` m${pt(op)}`;
    else if (op.startsWith("<lnTo>")) d += ` l${pt(op)}`;
    else if (op.startsWith("<cubicBezTo>")) {
      const pts = [...op.matchAll(/<pt x="([^"]*)" y="([^"]*)"/g)];
      d += ` c${pts.map((p) => ` ${p[1]} ${p[2]}`).join("")}`;
    } else if (op.startsWith("<quadBezTo>")) {
      const pts = [...op.matchAll(/<pt x="([^"]*)" y="([^"]*)"/g)];
      d += ` q${pts.map((p) => ` ${p[1]} ${p[2]}`).join("")}`;
    } else if (op.startsWith("<arcTo")) {
      d += ` a ${attr(op, "wR")} ${attr(op, "hR")} ${attr(op, "stAng")} ${attr(op, "swAng")}`;
    } else d += " x";
  }
  const fill = (attr(tag, "fill") as PathFill | undefined) ?? "norm";
  return {
    w: Number(attr(tag, "w") ?? 0),
    h: Number(attr(tag, "h") ?? 0),
    fill,
    stroke: attr(tag, "stroke") !== "false",
    d: d.trim(),
  };
};

const shapes: Record<string, ShapeDef> = {};
const shapeRe = /^ {2}<(\w+)>([\s\S]*?)^ {2}<\/\1>$/gm;
for (const [, name, block] of xml.matchAll(shapeRe)) {
  const paths: PathDef[] = [];
  const pathRe = /<path( [^>]*)?>([\s\S]*?)<\/path>/g;
  for (const [, tag, body] of block.matchAll(pathRe)) paths.push(encodePath(tag ?? "", body));
  // The spec default text rectangle is the full box ("l t r b") — skip it.
  const rectTag = block.match(/<rect ([^>]*)\/>/)?.[1];
  const rl = rectTag && (attr(rectTag, "l") ?? "l");
  const rt = rectTag && (attr(rectTag, "t") ?? "t");
  const rr = rectTag && (attr(rectTag, "r") ?? "r");
  const rb = rectTag && (attr(rectTag, "b") ?? "b");
  const trivial = rl === "l" && rt === "t" && rr === "r" && rb === "b";
  shapes[name] = {
    av: guides(block, "avLst"),
    gd: guides(block, "gdLst"),
    rect: rectTag && !trivial ? `${rl} ${rt} ${rr} ${rb}` : undefined,
    paths,
  };
}

const count = Object.keys(shapes).length;
const body = Object.entries(shapes)
  .map(([name, def]) => ` "${name}": ${JSON.stringify(def)}`)
  .join(",\n");
const out = `// Generated by scripts/generate-preset-shapes.ts from the ECMA-376 5th edition
// Part 1 distribution (OfficeOpenXML-DrawingMLGeometries.zip →
// presetShapeDefinitions.xml). Static spec data — regenerate only when the
// ECMA source updates. ahLst/cxnLst are dropped until something consumes them.
//
// Encoding consumed by the runtime evaluator (./preset-shape): av/gd entries
// are "name formula…" strings evaluated in order against the built-in guide
// set; each path is [w, h, fill, stroke, tokens] where w/h are the path
// coordinate-space dimensions (0 = the box itself) and tokens are the ops
// m(2) l(2) c(6) q(4) a(4) x(close) with guide-name/literal operands.

/** One preset path: coordinate-space size, fill mode, stroke flag, token stream. */
export interface PresetShapePathDef {
  /** Path coordinate-space width (0 = evaluate guides against the box width). */
  readonly w: number;
  /** Path coordinate-space height (0 = evaluate guides against the box height). */
  readonly h: number;
  readonly fill: "norm" | "none" | "darken" | "darkenLess" | "lighten" | "lightenLess";
  readonly stroke: boolean;
  /** Space-separated op tokens: m/l/c/q/a with guide-name or literal operands, x to close. */
  readonly d: string;
}

/** Static ECMA-376 definition of one preset geometry. */
export interface PresetShapeDef {
  /** Default adjustment values ("name formula…" strings). */
  readonly av: readonly string[];
  /** Guide formulas ("name formula…" strings), evaluated in order after av. */
  readonly gd: readonly string[];
  /** Text rectangle guide names ("l t r b" order); undefined = the full box. */
  readonly rect?: string;
  readonly paths: readonly PresetShapePathDef[];
}

export const PRESET_SHAPE_DEFS: Record<string, PresetShapeDef> = {
${body}
};
`;

const outFile = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "../src/layout/geometry/preset-shape-data.ts",
);
writeFileSync(outFile, out);
console.log(`${count} shapes → ${outFile}`);
console.log(`source: ${xml.length} bytes, generated: ${out.length} bytes`);
